// ---------------------------------------------- Begin: LOD system ----------------------------------------------
// This particle system demonstrates the LOD (= Level Of Detail) features. It uses a ramp function that increases
// or decreases the number of emitted particles, with, height, depth, .. depending on the distance between the 
// camera and the technique. Remarks:
// - This is only useful for a 1-camera setup. Applying particle system LOD isn't a good idea in a multi-camera
// setup, because there is only 1 version of the particle system active for both camera's. Splitting it up in
// multiple particle system versions isn't a good idea, because this introduces even more overhead.
// - The distance is calculated between the camera and the technique and not between the camera and the emitter or.
// between the camera and individual particles.
// ---------------------------------------------------------------------------------------------------------------
system lodSystem
{
	technique
	{
		// Use the billboard renderer defined in the *.pua script
		use_alias						$defaultBillboardRenderer
		material						Examples/Droplet
		
		// Particles become smaller if the camera is near
		default_particle_width			40 << camera_dependency
			{
				distance_threshold		700
				increase				true
			}
		default_particle_height			100 << camera_dependency
			{
				distance_threshold		700
				increase				true
			}

		visual_particle_quota			1000
		emitter							Box
		{
			// Emission rate decreses if the camera is further away
			emission_rate				30 << camera_dependency
				{
					distance_threshold	500
					increase			false
				}
			box_em_width				1000
			box_em_depth				1000
			angle						0
			position					0 400 0
			direction					0 -1 0
			velocity					120
			time_to_live				dyn_random
			{
				min						2
				max						4
			}
		}
	}
}
// ----------------------------------------------- End: LOD system -----------------------------------------------


// ---------------------------------------------- Begin: Advanced LOD system ----------------------------------------------
// This particle system demonstrates a more advanced LOD feature. It is similar to the Lod system in Ogre's material 
// system and particularly used if different renderers are used.
// Depending on the distance between the camera and the techniques, the appropriate technique is used.
// To prevent that the transition between the 2 techniques is abrupt, the smooth_lod feature is added. Smooth Lod 
// means that if a technique is outside the Lod distance, it doesn't emit new particles, but it still processes the 
// particles that are already emitted, which causes a smoother transition. The tradeoff of using Smooth Lod is, 
// that it only works correct with one camera.
// ---------------------------------------------------------------------------------------------------------------
system advancedLodSystem
{
	lod_distances						800 2200 2800
	smooth_lod							true
	technique
	{
		lod_index						0
		material						RustyBarrel
		default_particle_width			33
		default_particle_height			35
		default_particle_depth			35
		visual_particle_quota			100

		// Render barrel entities if the camera is near
		renderer						Entity
		{
			entity_renderer_mesh_name	Barrel.mesh
		}

		emitter							Box
		{
			emission_rate				5
			angle						25
			direction					0 1 0
			velocity					80
			time_to_live				dyn_random
			{
				min						2
				max						6
			}
		}
	}
	technique
	{
		lod_index						1
		material						ParticleUniverse/RustyBarrel
		default_particle_width			32
		default_particle_height			42
		visual_particle_quota           500

		// Render billboards with a barrel image if the camera is further away
		use_alias						$defaultBillboardRenderer

		emitter							Box
		{
			emission_rate				5
			angle						25
			direction					0 1 0
			velocity					80
			time_to_live				dyn_random
			{
				min						2
				max						6
			}
		}
	}
}
// ----------------------------------------------- End: Advanced LOD system -----------------------------------------------
