void main
(
  float4 iPosition : POSITION,
  float2 iTexCoord0 : TEXCOORD0,
  
  out float4 oPosition : POSITION,
  out float2 oTexCoord0 : TEXCOORD0,
  out float4 oColor : COLOR,

  uniform float4x4 worldViewProj,
  uniform float4 globalAmbient,
  uniform float4 matAmbient,
  uniform float4 matEmissive
)
{
  
  // transform position to projection space
  oPosition = mul(worldViewProj, iPosition);
    
  oTexCoord0 = iTexCoord0;
  oColor = (globalAmbient * matAmbient) + matEmissive;
}