// ---------------------------------------------------------------------------------------------------------------
system FXpression
{
	// Background
	technique
	{
		use_alias						$defaultBillboardRenderer
		material						ParticleUniverse/Star
		default_particle_width			400
		default_particle_height			400
		visual_particle_quota			1000
		emitter							Line
		{
			position					-800 600 0
			line_em_end					1600 600 0
			emission_rate				20
			angle						0
			direction					0 -1 0
			velocity					dyn_random
			{
				min						100
				max						400
			}
			time_to_live				10
		}
		affector						Colour
		{
			colour_aff_time_colour		0 0.3 0 0.1
			colour_aff_time_colour		1 0.3 0.3 0
		}
	}

	// Rotating mesh
	technique
	{
		default_particle_width			800
		default_particle_height			400
		default_particle_depth			40
		visual_particle_quota			10
		material						fxpression/ac3dmat1

		renderer						Entity
		{
			entity_renderer_mesh_name	fxpression.mesh
		}
		
		// Emit just 1 mesh
		emitter							Point
		{
			enabled						false
			emission_rate				1
			force_emission				true
			time_to_live				10
			repeat_delay				4
		}
		
		// Expire after a defined time and call another emitter
		observer						OnTime
		{
			on_time						greater_than 10.34
			since_start_system			true
			handler						DoPlacementParticle
			{
				force_emitter			LogoEmitter
				number_of_particles		1
			}
			handler						DoExpire{}
		}
		affector						Vortex
		{
			position					0 0 -500
			vortex_aff_vector			0 1 0
			vortex_aff_speed			2
		}
	}

	// Exploding mesh
	technique
	{
		default_particle_width			5
		default_particle_height			5
		default_particle_depth			5
		renderer						Box{}
		material						fxpression/ac3dmat1
		visual_particle_quota			5000
		emitted_emitter_quota			1

		// Emit just 1 other emitter
		emitter							Point					LogoEmitter
		{
			// Set emission_rate to 0 to wait until this emitter is called by the DoPlacementParticle event handler
			emission_rate				0
			force_emission				true
			emits						emitter_particle		Logo
			time_to_live				1
		}

		// Emit the mesh (as a number of blocks)
		emitter							MeshSurface				Logo
		{
			emission_rate				3000
			mesh_surface_scale			154 370 150
			force_emission				true
			auto_direction				true
			mesh_surface_mesh_name		fxpression.mesh
			mesh_surface_distribution	heterogeneous_2
			time_to_live				15
			velocity					dyn_random
			{
				min						10
				max						200
			}
		}
		affector						GeometryRotator
		{
			geom_rot_use_own_rotation	true
			geom_rot_rotation_speed		dyn_random
			{
				min						1
				max						20
			}
		}
	}
}
// ---------------------------------------------------------------------------------------------------------------
