// ---------------------------------------------- Begin: electricBeamSystem --------------------------------------
// This particle system demonstrates both:
// - the emission of particles along a trajectory path (a straight line that allows a small deviation of the 
//   particle position) 
// - the combination of the Align affector with the 'oriented_shape' property, which allows a particle to orientate 
//   itself towards the previous particle (and changes the particle height based on their mutual distance).
//   This enables the creation of a particle chain.
// ---------------------------------------------------------------------------------------------------------------
system electricBeamSystem
{
	technique
	{
		renderer Billboard
		{
			billboard_type				oriented_shape
			billboard_origin			bottom_center
		}
		material						ParticleUniverse/Lightning
		default_particle_width			35
		default_particle_height			0
		visual_particle_quota			500
		emitter							Line
		{
			line_em_end					1500 300 0
			line_em_min_increment		50
			line_em_max_increment		150
			line_em_max_deviation		10
			emission_rate				40
			time_to_live				100
		}

		affector						Line
		{
			line_aff_max_deviation		140
			line_aff_time_step			0.03
			line_aff_end				1500 300 0
			line_aff_drift				0.3
		}
		
		affector						Align
		{
			align_aff_resize			true
		}
	}


	// We take a second technique for the other beam
	technique
	{
		renderer Billboard
		{
			billboard_type				oriented_shape
			billboard_origin			bottom_center
		}
		material						ParticleUniverse/Lightning
		default_particle_width			15
		default_particle_height			0
		visual_particle_quota			500
		emitter							Line
		{
			line_em_end					1500 300 0
			line_em_min_increment		30
			line_em_max_increment		60
			line_em_max_deviation		30
			emission_rate				150
			time_to_live				100
		}

		affector						Line
		{
			line_aff_max_deviation		200
			line_aff_time_step			0.01
			line_aff_end				1500 300 0
			line_aff_drift				0.1
		}
		
		affector						Align
		{
			align_aff_resize			true
		}
	}
}
// ----------------------------------------------- End: electricBeamSystem ---------------------------------------
