
def header_files( version ):
    return ["Ogre.h",
            "OgreColourValue.h",
            "OgreWireBoundingBox.h",
            "OgrePagingLandScapePreCompiledHeaders.h",
            "OgrePagingLandScapePrerequisites.h",
            "OgrePagingLandScapeOctreeSceneManager.h",
            "OgrePagingLandScapeOctreeNode.h",
            "OgrePagingLandScapeOctree.h",
            "OgrePagingLandScapeOctreeCamera.h",
            "OgrePagingLandScapeOctreeAxisAlignedBoxSceneQuery.h",
            "OgrePagingLandScapeOctreeIntersectionSceneQuery.h",
            "OgrePagingLandScapeOctreePlaneBoundedVolumeListSceneQuery.h",
            "OgrePagingLandScapeOctreeRaySceneQuery.h",
            "OgrePagingLandScapeOctreeSphereSceneQuery.h",
            "OgreOcclusionBoundingBox.h",
            "OgrePagingLandScapeOcclusionQuerySet.h",
            "OgrePagingLandScapeOcclusionSorter.h",
            "OgrePagingLandScapeOcclusionTraversal.h",
            "OgrePagingLandScapeOcclusionCameraTraversal.h",
            "OgrePagingLandScapeOcclusionDebugTraversal.h",
            "OgrePagingLandScapeOcclusionCHCTraversal.h",
            "OgrePagingLandScapeOcclusionSWTraversal.h",
            "OgrePagingLandScapeOcclusionVFTraversal.h",
            "OgrePagingLandScapeOcclusion.h",
            "OgrePagingLandScapeOcclusionElement.h",
            "OgrePagingLandScapeOcclusionVisibilityData.h",
            "OgrePagingLandScapeSceneManager.h",
            "OgrePagingLandScapeOptions.h",
            "OgrePagingLandScapeCamera.h",
            "OgrePagingLandScapeRaySceneQuery.h",
            "OgrePagingLandScapeIntersectionSceneQuery.h",
            "OgrePagingLandScapeAxisAlignedBoxSceneQuery.h",
            "OgrePagingLandScapeHorizon.h",
            "OgrePagingLandScapePage.h",
            "OgrePagingLandScapePageRenderable.h",
            "OgrePagingLandScapePageManager.h",
            "OgrePagingLandScapeTile.h",
            "OgrePagingLandScapeTileInfo.h",
            "OgrePagingLandScapeTileManager.h",
            "OgrePagingLandScapeIndexBuffer.h",
            "OgrePagingLandScapeTextureCoordinatesManager.h",
            "OgrePagingLandScapeRenderable.h",
            "OgrePagingLandScapeRenderableManager.h",
            "OgrePagingLandScapeData2D.h",
            "OgrePagingLandScapeData2D_HeightField.h",
            "OgrePagingLandScapeData2D_HeightFieldTC.h",
            "OgrePagingLandScapeData2D_HeightFieldN.h",
            "OgrePagingLandScapeData2D_HeightFieldNTC.h",
            "OgrePagingLandScapeData2D_HeightFieldRaw.h",
            "OgrePagingLandScapeData2D_HeightFieldRawTC.h",
            "OgrePagingLandScapeData2D_Spline.h",
            "OgrePagingLandScapeData2DManager.h",
            "OgrePagingLandScapeTexture.h",
            "OgrePagingLandScapeTexture_Splatting.h",
            "OgrePagingLandScapeTexture_BaseTexture.h",
            "OgrePagingLandScapeTextureManager.h",
            "OgrePagingLandScapeListenerManager.h",
            "OgrePagingLandScapeListener.h",
            "OgrePagingLandScapeCallback.h",
            "OgrePagingLandScapeCallbackEvent.h",
            "OgrePagingLandScapeMeshDecal.h",
            "OgrePagingLandScapePoolSet.h",
            "OgrePagingLandScapeQueue.h",
            "OgreDebugRectangle2D.h",
            "fileutils.h",
            "PagingLandScape2TerrainListener.h"
            ]



##ifndef _PLSM_OCTREE
#	"OgreOctreeSceneManager.h",
##endif

            
def huge_classes( version ):
    return []
   