export PKG_CONFIG_PATH=":/home/andy/development/root/usr/lib/pkgconfig:/home/andy/development/root/usr/lib/pkgconfig"
export LD_LIBRARY_PATH="/home/andy/development/root/usr/lib"
export CFLAGS="-I/home/andy/development/root/usr/include -L/home/andy/development/root/usr/lib"
export CXXFLAGS="-I/home/andy/development/root/usr/include -L/home/andy/development/root/usr/lib"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/andy/development/root/usr/bin:/home/andy/development/root/usr/bin"
export PYTHONPATH="/home/andy/development/root/usr/lib/python2.5/site-packages"
